name: Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout code 
        uses: actions/checkout@v3
        
      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npx firebase deploy --project greenhousespa-9b028    
